spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://120.25.120.99:59999;databaseName=db_cjy
    username: cjy_user
    password: dba@cjy
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
          hibernate:
            dialect: org.hibernate.dialect.SQLServer2008Dialect
server:
  port: 7777


